## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux'


# data folder and alternate, so local and MCO machine paths get tried
data_folder = '/media/research/IrrigationGIS/swim'
alt_data_folder = '/home/dgketchum/data/IrrigationGIS/swim'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2000-01-01'
end_date = '2023-12-31'

## Static file names; prepend with data_folder
input_data = 'examples/tongue_annex/prepped_input/tongue_input_sample.json'
## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration

calibration_dir = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue_annex/pest/mult'
initial_values_csv = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue_annex/params.csv'

[FORECAST]

forecast_parameters = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue_annex/master/flux.5.par.csv'
