import os


TRACKER_PARAMS = ['taw',
                  'taw3',
                  'melt',
                  'rain',
                  'snow_fall',
                  'daw3',
                  'daw3_prev',
                  'aw3',
                  'aw',
                  'cum_evap',
                  'cum_evap_prev',
                  'depl_ze',
                  'dperc',
                  'depl_root',
                  'depl_root_prev',
                  'soil_water',
                  'soil_water_prev',
                  'etc_act',
                  'fc',
                  'gw_sim',
                  'irr_sim',
                  'kc_act',
                  'kc_max',
                  'kc_min',
                  'kc_bas',
                  'kc_bas_mid',
                  'ke',
                  'ke_max',
                  'kr',
                  'kr_prev',
                  'ks',
                  'ks_prev',
                  'mad',
                  'max_irr_rate',
                  'next_day_irr',
                  'niwr',
                  'p_rz',
                  'p_eft',
                  'ppt_inf',
                  'ppt_inf_prev',
                  'rew',
                  'tew',
                  'sro',
                  'swe',
                  'zr',
                  'zr_mult',
                  'zr_min',
                  'zr_max',
                  'totwatin_ze',
                  'wt_irr',
                  'irr_min']


if __name__ == '__main__':
    pass
# ========================= EOF ====================================================================
