import os


TRACKER_PARAMS = ['taw',
                  'taw3',
                  'albedo',
                  'min_albedo',
                  'melt',
                  'rain',
                  'snow_fall',
                  'daw3',
                  'daw3_prev',
                  'aw3',
                  'cn2',
                  'cgdd',
                  'aw',
                  'cgdd_penalty',
                  'cum_evap',
                  'ad',
                  'cum_evap_prev',
                  'depl_ze',
                  'dperc',
                  'dperc_ze',
                  'density',
                  'depl_root',
                  'depl_root_prev',
                  'soil_water',
                  'soil_water_prev',
                  'etc_act',
                  'etc_pot',
                  'etc_bas',
                  'etref_30',
                  'fc',
                  'grow_root',
                  'gw_sim',
                  'height_min',
                  'height_max',
                  'height',
                  'irr_sim',
                  'kc_act',
                  'kc_pot',
                  'kc_max',
                  'kc_min',
                  'kc_bas',
                  'kc_bas_mid',
                  'ke',
                  'kr',
                  'ks',
                  'mad',
                  'max_irr_rate',
                  'next_day_irr',
                  'niwr',
                  'p_rz',
                  'p_eft',
                  'ppt_inf',
                  'ppt_inf_prev',
                  'rew',
                  'tew',
                  's',
                  's1',
                  's2',
                  's3',
                  's4',
                  'sro',
                  'swe',
                  'zr',
                  'zr_mult',
                  'zr_min',
                  'zr_max',
                  'invoke_stress',
                  'doy_start_cycle',
                  'cutting',
                  'cycle',
                  'height_initial',
                  'height_max',
                  'height_min',
                  'height',
                  'totwatin_ze',
                  'cgdd_at_planting',
                  'wt_irr',
                  'irr_min']


if __name__ == '__main__':
    pass
# ========================= EOF ====================================================================
