project = "4_Flux_Network"
root = "/data/ssd2/swim"

[paths]
project_workspace = "{root}/{project}"
data = "{project_workspace}/data"

landsat = "{data}/landsat"
landsat_ee_data = "{landsat}/extracts"
landsat_tables = "{landsat}/tables"

sentinel = "{data}/sentinel"
sentinel_ee_data = "{sentinel}/extracts"
sentinel_tables = "{sentinel}/tables"

met = "{data}/met_timeseries/gridmet"

gis = "{data}/gis"
footprint_shapefile = "{gis}/flux_footprints_3p_clean.shp"
gridmet_mapping = "{gis}/flux_fields_gfid.shp"

correction_tifs = "{data}/bias_correction_tif"
gridmet_factors = "{gis}/flux_fields_gfid.json"

properties = "{data}/properties"
irr = "{properties}/{project}_irr.csv"
ssurgo = "{properties}/{project}_ssurgo.csv"
lulc = "{properties}/{project}_landcover.csv"
properties_json = "{properties}/{project}_properties.json"

snodas_in = "{data}/snodas/extracts"
snodas_out = "{data}/snodas/snodas.json"

remote_sensing_tables = "{data}/rs_tables"
joined_timeseries = "{data}/plot_timeseries"
dynamics_data = "{data}/{project}_dynamics.json"
station_metadata = "{data}/station_metadata.csv"
station_file = "{data}/station_metadata.csv"
prepped_input = "{data}/prepped_input.json"

[earth_engine]
fields_flux = "projects/ee-dgketchum/assets/swim/flux_footprints_3p_clean"
bucket = "wudr"

[ids]
feature_id = "site_id"
gridmet_mapping_index = "site_id"
state_col = "state"

[misc]
irrigation_threshold = 0.3
elev_units = "m"
refet_type = "eto"
swb_mode = "cn"

[date_range]
start_date = "1987-01-01"
end_date = "2024-12-31"

[crop_coefficient]
kc_proxy = "etf"
cover_proxy = "ndvi"

[calibration]
pest_run_dir = "{project_workspace}/pestrun"
etf_target_model = 'ssebop'
#etf_ensemble_members = ["eemetric", "geesebal", "ptjpl", "sims", "ssebop", "disalexi"]
workers = 20
realizations = 200
calibration_dir = "{pest_run_dir}/pest/mult"
obs_folder = "{pest_run_dir}/obs"
initial_values_csv = "{pest_run_dir}/params.csv"
spinup = '{pest_run_dir}/spinup.json'
source_python_script = '/home/dgketchum/code/swim-rs/tutorials/4_Flux_Network/custom_forward_run.py'

[forecast]
forecast_parameters = "{pest_run_dir}/master/4_Flux_Network.3.par.csv"
