## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux'
input_nc = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux/input.nc'


# data folder and alternate, so local and MCO machine paths get tried
data_folder = '/media/research/IrrigationGIS/swim'
alt_data_folder = '/home/dgketchum/data/IrrigationGIS/swim'

# fields data; prepend with data_folder
fields_path = 'examples/flux/prepped_input/flux_input_sample.json'

field_index = 'field_1'
shapefile = '{project_root}/data/gis/flux_fields.shp'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2000-01-01'
end_date = '2023-12-31'

## Static file names; prepend with data_folder
input_data = 'examples/flux/prepped_input/flux_input_sample.json'
## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration

calibration_dir = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux/pest/mult'
initial_values_csv = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux/params.csv'

[FORECAST]
forecast_flag = 1
forecast_parameters = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux/master/flux.5.par.csv'
