## SWIM Configuration
[FIELDS]
project_name = '1_Boulder'
project_folder = '{project_root}/step_5_model_run'

## data folder and alternate, to check another location if necessary
data_folder = '{project_root}/data'
obs_folder = '{project_root}/obs'

## The unique identifier from the original project shapefile that identifies sample plots (fields)
field_index = 'FID_1'
shapefile = '{project_root}/data/gis/mt_sid_boulder.shp'

## Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2004-01-01'
end_date = '2022-12-31'

## Static file names; prepend with data_folder
input_data = '{project_root}/data/prepped_input.json'
plot_timeseries = '{project_root}/data/plot_timeseries'

## Misc configs
elev_units = 'm'
refet_type = 'eto'

## Below the irrigation threshold, the model will analyze the unirrigated portion
irr_threshold = 0.3

[CALIBRATION]
## PEST Calibration (0: calibrating, 1: not calibrating)

calibration_dir = ''
initial_values_csv = ''

[FORECAST]
## Forecast means we're running with PEST++ calibrated parameters

forecast_parameters = ''
