"""
Visualization utilities for SWIM-RS model outputs.

Provides color maps and plotting utilities for displaying model results.

Attributes:
    COLOR_MAP: Dictionary mapping variable names to matplotlib colors.
        Used for consistent styling across plots.
"""

COLOR_MAP = {
    "et_act": "blue",
    "etref": "green",
    "kc_act": "lightsalmon",
    "kc_bas": "purple",
    "ks": "yellow",
    "ke": "purple",
    "melt": "lightblue",
    "rain": "lightpink",
    "depl_root": "grey",
    "depl_ze": "darkgrey",
    "dperc": "sandybrown",
    "runoff": "red",
    "delta_soil_water": "teal",
    "wbal": "black",
    "ppt": "lightcyan",
    "snow_fall": "blue",
    "taw": "darkorange",
    "taw3": "orangered",
    "daw3": "yellow",
    "delta_daw3": "gold",
    "swe": "skyblue",
    "tavg": "darkblue",
    "tmax": "red",
    "irrigation": "red",
    "gw_sim": "darkgreen",
    "fc": "forestgreen",
    "t": "turquoise",
    "e": "mediumseagreen",
    "few": "lightgreen",
    "zr": "darkseagreen",
    "p_rz": "mediumspringgreen",
    "p_eft": "springgreen",
    "soil_water": "seagreen",
    "niwr": "limegreen",
    "irr_day": "lime",
    "season": "greenyellow",
    "capture": "green",
    "doy": "yellow",
    "tmin_c": "blue",
    "tmax_c": "red",
    "srad_": "orange",
    "obs_swe": "blue",
    "prcp": "pink",
    "nld_ppt_d": "lightpink",
    "prcp_hr_00": "grey",
    "prcp_hr_01": "grey",
    "prcp_hr_02": "grey",
    "prcp_hr_03": "grey",
    "prcp_hr_04": "grey",
    "prcp_hr_05": "grey",
    "prcp_hr_06": "grey",
    "prcp_hr_07": "grey",
    "prcp_hr_08": "grey",
    "prcp_hr_09": "grey",
    "prcp_hr_10": "grey",
    "prcp_hr_11": "grey",
    "prcp_hr_12": "grey",
    "prcp_hr_13": "grey",
    "prcp_hr_14": "grey",
    "prcp_hr_15": "grey",
    "prcp_hr_16": "grey",
    "prcp_hr_17": "grey",
    "prcp_hr_18": "grey",
    "prcp_hr_19": "grey",
    "prcp_hr_20": "grey",
    "prcp_hr_21": "grey",
    "prcp_hr_22": "grey",
    "prcp_hr_23": "grey",
    "etr": "green",
    "eto": "yellowgreen",
    "etf_irr": "blue",
    "ndvi_irr": "green",
    "etf_irr_ct": "blue",
    "ndvi_irr_ct": "green",
    "etr_uncorr": "lightgreen",
    "eto_uncorr": "darkseagreen",
    "etf_inv_irr": "blue",
    "ndvi_inv_irr": "green",
    "etf_inv_irr_ct": "blue",
    "ndvi_inv_irr_ct": "green",
    "ndvi": "mediumseagreen",
    "ndvi_ct": "green",
    "etf": "blue",
    "etf_ct": "blue",
    "pdc": "purple",
    "flux_etf": "magenta",
    "ssebop": "grey",
    "disalexi": "pink",
    "geesebal": "magenta",
    "eemetric": "red",
    "ptjpl": "yellow",
    "sims": "green",
}
